# Generated by Django 3.2.23 on 2023-12-30 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'verbose_name_plural': 'アイテム'},
        ),
        migrations.AlterModelOptions(
            name='owneditem',
            options={'verbose_name_plural': '所有アイテム'},
        ),
        migrations.AlterModelTable(
            name='item',
            table='items',
        ),
        migrations.AlterModelTable(
            name='owneditem',
            table='owned_items',
        ),
    ]
