version: '3'

services:
    backend:
        build:
            context: ./backend_Project
            dockerfile: docker/python/Dockerfile
        command: python3 /backend/manage.py runserver 0.0.0.0:8000
        volumes:
            - ./backend_Project/backend:/backend
        ports:
            - "8000:8000"
        tty: true
        depends_on:
            - db


    frontend:
        build:
          context: ./frontend_Project
          dockerfile: docker/node/Dockerfile
        volumes:
          - ./frontend_Project/node/frontend:/usr/src/app/frontend
        command: sh -c "cd /usr/src/app/frontend && yarn start"
        ports:
          - "3000:3000"

    db:
        image: mariadb:latest
        container_name: my_mariadb
        environment:
          MYSQL_DATABASE: main
          MYSQL_USER: root
          MYSQL_PASSWORD: password
          MYSQL_ROOT_PASSWORD: password
        ports:
          - "3307:3306"
        volumes:
          - ./.dbdata:/var/lib/mysql

