# Generated by Django 3.2.23 on 2023-12-26 11:43

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), '半角英数字とアンダースコア,ハイフンのみ使用できます', 'invalid')], verbose_name='ユーザーID'),
        ),
    ]
